greeting:
  description: |
    Greeting utility.
    Let your terminal greets you.
  opts:
    greet:
      description: "How to greet"
      type: enum
      elements:
        - Ciao
        - Hello
        - Hola
        - Ni Hao
    name:
      type: text
      description: Who should we greet?
      default: World
  exec: |
    echo Let me do a greeting!
    echo $greet $name
arguments-showcase:
  description: Examples of various 'opts' and 'flags'
  opts:
    afolder:
      description: Pick a folder from your home (~/)
      type: folder
      path: ~/
    afile:
      description: Pick a go file from current folder
      type: file
      pattern: '*.go'
  flags:
    verbose:
      description: Verbose output
      values:
        text: The verbose flag was set, so the 'text' variable will be present in the script execution
  exec: |
    cat $afile
    echo $afolder
    tree ~/$afolder
    if [ ! -z "$text" ]
    then
      echo "Verbose mode on"
      echo $text
    fi
    echo DONE